debug: ${debug} # inherited from configurations/config.yaml
lr: ${experiment.training.lr}

# dataset-dependent configurations
x_shape: ${dataset.observation_shape}
frame_stack: 1
data_mean: ${dataset.data_mean}
data_std: ${dataset.data_std}
external_cond_dim: 4 #${dataset.action_dim}
context_frames: ${dataset.context_length}
uncertainty_scale: 1
guidance_scale: 0.0
chunk_size: 1 # -1 for full trajectory diffusion, number to specify diffusion chunk size
noise_level: random_all
causal: True

n_frames: ${dataset.n_frames}
frame_skip: ${dataset.frame_skip}
metadata: ${dataset.metadata}

# training hyperparameters
weight_decay: 2e-3
warmup_steps: 10000
optimizer_beta: [0.9, 0.99]

save_video_every_n_step: 1000 # save a video every n train steps

diffusion:
# training
  schedule_fn_kwargs: {}
  use_snr: False
  use_cum_snr: False
  snr_clip: 5.0
  timesteps: 1000
  beta_schedule: sigmoid
  objective: pred_v
  use_fused_snr: True
  cum_snr_decay: 0.96
  clip_noise: 6.
  # sampling
  sampling_timesteps: 100 # fixme, numer of diffusion steps, should be increased
  ddim_sampling_eta: 0.0
  stabilization_level: 15
  # architecture
  architecture:
    network_size: 64
    attn_heads: 4
    attn_dim_head: 64
    dim_mults: [1, 2, 4, 8]
    resolution: ${dataset.resolution}
    attn_resolutions: [16, 32, 64, 128]
    use_init_temporal_attn: True
    use_linear_attn: True
    time_emb_type: rotary

metrics:
  - fvd
  # - fid
  # - lpips