debug: ${debug} # inherited from configurations/config.yaml
metadata: "data/minecraft_video/minecraft/metadata.json"

save_dir: data/minecraft_video/minecraft
n_frames: 10 # TODO: increase later
resolution: &resolution 64
data_mean: 0.5
data_std: 0.5
external_cond_dim: 4
context_length: 2
frame_skip: 2
validation_multiplier: 1
observation_shape: [3, *resolution, *resolution]